package:
    name: marvin
    version: 0.1.0  

build:
    number: 0

source:
    url: https://github.com/Illumina/MarViN/archive/v0.1.0.tar.gz
    sha256: 381aaf979e4840b6ecd5046e2186a9b08f16fa49b6b2415778c1953793894bb0

requirements:
    build:
        - {{ compiler('c') }}

test:
    commands:
        - marvin 2>&1 | grep "Expects input.vcf to contain GLs/PLs."
        - marvin_prep 2>&1 | grep "Expects input_filename.vcf to contain hard genotypes only"

about:
    home: https://github.com/illumina/marvin
    license: file
    license_file: LICENSE.txt
    summary: Algorithm that models  linkage-disequilibrium (LD) using a simple multivariate Gaussian distribution.
extra:
    identifiers:
        - biotools:MarViN
        - doi:10.1093/bioinformatics/btw097
