{% set version = "0.26.0" %}
{% set name = "rSFFreader" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: b34cefd465eaf5e067ef44c3a13554ae40530e7b8a97b991ca202d2b8f2955a8
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biostrings
    - bioconductor-iranges
    - 'bioconductor-s4vectors >=0.13.8'
    - 'bioconductor-shortread >=1.23.17'
    - bioconductor-xvector
    - r-base
    - gcc  # [linux]
    - llvm  # [osx]
  run:
    - bioconductor-biostrings
    - bioconductor-iranges
    - 'bioconductor-s4vectors >=0.13.8'
    - 'bioconductor-shortread >=1.23.17'
    - bioconductor-xvector
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'rSFFreader reads sequence, qualities and clip point values from sff files generated by Roche 454 and Life Sciences Ion Torrent sequencers into similar classes as are present for fastq files.'
