{% set version = "1.18.0" %}
{% set name = "plrs" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: daadaaed803e2faabb06c8773899ddd0e5f5198c929f7695dea28083eddc2879
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-cghbase
    - bioconductor-marray
    - r-base
    - r-ic.infer
    - r-quadprog
    - r-rcsdp
  run:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-cghbase
    - bioconductor-marray
    - r-base
    - r-ic.infer
    - r-quadprog
    - r-rcsdp
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>=2.0)'
  summary: 'The present package implements a flexible framework for modeling the relationship between DNA copy number and gene expression data using Piecewise Linear Regression Splines (PLRS).'
