{% set version = "1.47.0" %}
{% set name = "pdmclass" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: c368da4631ee99892f8304ba95ff87dfb03f96d70b0d73628f1c7a64bd0b2cbf
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-biobase >=1.4.22'
    - bioconductor-fibroeset
    - r-base
    - r-mda
  run:
    - 'bioconductor-biobase >=1.4.22'
    - bioconductor-fibroeset
    - r-base
    - r-mda
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'This package can be used to classify microarray data using one of three penalized regression methods; partial least squares, principal components regression, or ridge regression.'
