{% set version = "2.12.0" %}
{% set name = "GOsummaries" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 9a28b1dcf691542cdad07890ca84c9944ed38fb77ee06377e102334ee9c91fab
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-limma
    - r-base
    - r-ggplot2
    - r-gprofiler
    - r-gtable
    - r-plyr
    - r-rcpp
    - r-reshape2
    - gcc  # [linux]
    - llvm  # [osx]
  run:
    - bioconductor-limma
    - r-base
    - r-ggplot2
    - r-gprofiler
    - r-gtable
    - r-plyr
    - r-rcpp
    - r-reshape2
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'A package to visualise Gene Ontology (GO) enrichment analysis results on gene lists arising from different analyses such clustering or PCA. The significant GO categories are visualised as word clouds that can be combined with different plots summarising the underlying data.'
