package:
    name: pscan
    version: 1.5  

build:
    number: 0

source:
    url: http://159.149.160.88/pscan/Source/pscan.tar.gz
    sha256: b59cac9effcad6ab286372a95e81a57a226ceb2a4a267ffa93bc084467fdf92b
    patches: 
        - pscan.patch

requirements:
    build:
        - {{ compiler('cxx') }}
    host:
        - gsl
test:
    commands:
        - pscan -h | xargs echo

about:
    home: http://www.beaconlab.it/pscan
    license: file
    license_file: LICENSE.txt
    summary: Software tool that scans a set of sequences (e.g. promoters) from co-regulated or co-expressed genes with motifs describing the binding specificity of known transcription factors and assesses which motifs are significantly over- or under-represented, providing thus hints on which transcription factors could be common regulators of the genes studied, together with the location of their candidate binding sites in the sequences
extra:
    identifiers:
        - biotools:beaconlab_pscan
        - doi:10.1093/nar/gkp464
