{% set version = "1.4.0" %}
{% set name = "uSORT" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 7bf12cd642f2b90f1df9c41f88ff4d4e37d4f6be51b3326529c096a46cea267f
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-monocle
    - r-base
    - r-cluster
    - r-fpc
    - r-gplots
    - r-igraph
    - r-matrix
    - r-plyr
    - r-rann
    - r-rspectra
    - r-vgam
  run:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-monocle
    - r-base
    - r-cluster
    - r-fpc
    - r-gplots
    - r-igraph
    - r-matrix
    - r-plyr
    - r-rann
    - r-rspectra
    - r-vgam
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'This package is designed to uncover the intrinsic cell progression path from single-cell RNA-seq data. It incorporates data pre-processing, preliminary PCA gene selection, preliminary cell ordering, feature selection, refined cell ordering, and post-analysis interpretation and visualization.'
