package:
    name: qtdt
    version: 2.6.1  

build:
    number: 0

source:
    url: http://csg.sph.umich.edu/abecasis/qtdt/download/qtdt-2.6.1.tar.gz
    sha256: ab0eeea3f3f4f180333ec481a355d3a31dc5566607292cb51bdb34cf3b2ede2c

requirements:
    build:
        - {{ compiler('c') }}

test:
    commands:
        - qtdt 2>&1 | grep "(c) 1998-2007 Goncalo Abecasis (goncalo@umich.edu)"

about:
    home: http://csg.sph.umich.edu/abecasis/qtdt/
    license: file
    license_file: LICENSE.twister
    summary: It provides a one-stop interface for family based tests of linkage disequilibrium. The general models are supported, and can be used to analyse quantitative or discrete traits in nuclear families, with or without parental genotypes, or extended pedigrees. In addition, QTDT can calculate exact p-values by permutation even when multiple linked polymorphisms are tested.
extra:
    identifiers:
        - biotools:QTDT
        - doi:10.1086/302698
