{% set version = "1.10.0" %}
{% set name = "RUVcorr" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 620fe9c7756995b987a5d542e60d9addc2d555bbab67eb7b7b8d7cd213fa175a
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biocparallel
    - bioconductor-bladderbatch
    - r-base
    - r-corrplot
    - r-gridextra
    - r-lattice
    - r-mass
    - r-psych
    - r-reshape2
    - r-snowfall
  run:
    - bioconductor-biocparallel
    - bioconductor-bladderbatch
    - r-base
    - r-corrplot
    - r-gridextra
    - r-lattice
    - r-mass
    - r-psych
    - r-reshape2
    - r-snowfall
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'RUVcorr allows to apply global removal of unwanted variation (ridged version of RUV) to real and simulated gene expression data.'
