package:
  name: python-grok
  version: 1.1.1  

build:
  number: 0
  skip: True # [not py2k] 

source:
  url: http://csbi.ltdk.helsinki.fi/grok/files/grok-1.1.1.tar.gz
  sha256: d6510fb22f1d77897a6ff8513d7d531b14ff737e7b2c71fda41988b64dd39d5f

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - zlib
    - python
  run:
    - python
    - zlib

test:
  import:
    - grok
about:
  home: http://csbi.ltdk.helsinki.fi/grok/
  license: file
  license_file: COPYING
  summary: This tool is “Swiss Army knife” library for processing genomic interval data. It operates on genomic regions, annotated chromosomal intervals that represent sequencing short reads, gene locations, ChIP-seq peaks or other genomic features. Applications of GROK include file format conversions, set operations, overlap queries, and filtering and transformation operations. Supported file formats include BAM/SAM, BED, BedGraph, CSV, FASTQ, GFF/GTF, VCF and Wiggle.
extra:
  identifiers:
    - biotools:GROK
    - doi:10.1109/TCBB.2012.170


