{% set version = "1.10.0" %}
{% set name = "metagenomeFeatures" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 7b16215cf15428822942ffff1c9f605eb15c7ad44885c0d8145cedc4772314b1
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-biobase >=2.17.8'
    - 'bioconductor-biostrings >=2.36.4'
    - 'bioconductor-metagenomeseq >=1.14.2'
    - 'bioconductor-shortread >=1.26.0'
    - 'r-ape >=3.5'
    - r-base
    - 'r-dbplyr >=1.0.0'
    - 'r-dplyr >=0.7.0'
    - 'r-lattice >=0.20.33'
    - 'r-lazyeval >=0.1.10'
    - 'r-magrittr >=1.5'
    - 'r-purrr >=0.2.2'
    - 'r-rsqlite >=1.0.0'
    - 'r-stringr >=1.0.0'
  run:
    - 'bioconductor-biobase >=2.17.8'
    - 'bioconductor-biostrings >=2.36.4'
    - 'bioconductor-metagenomeseq >=1.14.2'
    - 'bioconductor-shortread >=1.26.0'
    - 'r-ape >=3.5'
    - r-base
    - 'r-dbplyr >=1.0.0'
    - 'r-dplyr >=0.7.0'
    - 'r-lattice >=0.20.33'
    - 'r-lazyeval >=0.1.10'
    - 'r-magrittr >=1.5'
    - 'r-purrr >=0.2.2'
    - 'r-rsqlite >=1.0.0'
    - 'r-stringr >=1.0.0'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'metagenomeFeatures was developed for use in exploring the taxonomic annotations for a marker-gene metagenomic sequence dataset. The package can be used to explore the taxonomic composition of a marker-gene database or annotated sequences from a marker-gene metagenome experiment.'
