package:
  name: ocg
  version: 1.0

source:
  fn: OCG_1.0_Becker_et_al.tgz
  url: http://tagc.univ-mrs.fr/tagc/download/Software/OCG/OCG_1.0_Becker_et_al.tgz
  sha256: 42d303ba55abde0cbb48ec3fd6b075e27164e9c9060b34c9fd64cdb2431174ba

requirements:
  build:
    - gcc
  run:
    - libgcc

test:
  commands:
    - './../work_moved_ocg-1.0-0_linux-64/OCG -h'

about:
    home: 'http://tagc.univ-mrs.fr/tagc/index.php/software/17'
    license: GLP3
    summary: "Overlapping Cluster Generator (OCG)"