{% set version = "1.24.0" %}
{% set name = "isobar" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 69d64f5f753209567aa256bd1dbbe56e4c3c468172da50f1e0383a02f4e447d8
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biobase
    - bioconductor-biomart
    - r-base
    - r-distr
    - r-ggplot2
    - r-plyr
  run:
    - bioconductor-biobase
    - bioconductor-biomart
    - r-base
    - r-distr
    - r-ggplot2
    - r-plyr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: LGPL-2
  summary: 'isobar provides methods for preprocessing, normalization, and report generation for the analysis of quantitative mass spectrometry proteomics data labeled with isobaric tags, such as iTRAQ and TMT. Features modules for integrating and validating PTM-centric datasets (isobar-PTM). More information on http://www.ms-isobar.org.'
