{% set version = "1.10.0" %}
{% set name = "MatrixRider" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: e506fad2aa55c96678172da3de3357ae09e3bb8cff07d626a2c9be3a20e0ba1e
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biostrings
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-tfbstools
    - bioconductor-xvector
    - r-base
    - gcc  # [linux]
    - llvm  # [osx]
  run:
    - bioconductor-biostrings
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-tfbstools
    - bioconductor-xvector
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'Calculates a single number for a whole sequence that reflects the propensity of a DNA binding protein to interact with it. The DNA binding protein has to be described with a PFM matrix, for example gotten from Jaspar.'
