{% set version = "1.10.5" %}
{% set name = "RnBeads" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 991ae31e196032f4e148fda1728953389f418b58318ec030d56426cceec0d036
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biocgenerics
    - bioconductor-genomicranges
    - bioconductor-illuminaio
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-methylumi
    - 'bioconductor-s4vectors >=0.9.25'
    - r-base
    - r-cluster
    - r-ff
    - r-fields
    - 'r-ggplot2 >=0.9.2'
    - r-gplots
    - r-gridextra
    - r-mass
    - r-matrixstats
    - r-plyr
  run:
    - bioconductor-biocgenerics
    - bioconductor-genomicranges
    - bioconductor-illuminaio
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-methylumi
    - 'bioconductor-s4vectors >=0.9.25'
    - r-base
    - r-cluster
    - r-ff
    - r-fields
    - 'r-ggplot2 >=0.9.2'
    - r-gplots
    - r-gridextra
    - r-mass
    - r-matrixstats
    - r-plyr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'RnBeads facilitates comprehensive analysis of various types of DNA methylation data at the genome scale.'
