{% set version = "1.32.0" %}
{% set name = "ChIPseqR" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 1be73262e3aec63819fdb5ef1188bd3ce4d1c260e3f9a6dbc913e657b2a3f845
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biocgenerics
    - bioconductor-biostrings
    - bioconductor-genomicranges
    - bioconductor-hilbertvis
    - 'bioconductor-iranges >=2.5.14'
    - 'bioconductor-s4vectors >=0.9.25'
    - bioconductor-shortread
    - r-base
    - r-fbasics
    - r-timsac
    - gcc  # [linux]
    - llvm  # [osx]
  run:
    - bioconductor-biocgenerics
    - bioconductor-biostrings
    - bioconductor-genomicranges
    - bioconductor-hilbertvis
    - 'bioconductor-iranges >=2.5.14'
    - 'bioconductor-s4vectors >=0.9.25'
    - bioconductor-shortread
    - r-base
    - r-fbasics
    - r-timsac
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'ChIPseqR identifies protein binding sites from ChIP-seq and nucleosome positioning experiments. The model used to describe binding events was developed to locate nucleosomes but should flexible enough to handle other types of experiments as well.'
