{% set version = "1.9.0" %}
{% set name = "OperaMate" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 557333415491092489e58072ca6feb8d60a8c91a9fcd373044f5114075295085
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r-base
    - r-fbasics
    - r-ggplot2
    - r-gprofiler
    - r-gridextra
    - r-pheatmap
    - r-reshape2
    - r-stabledist
  run:
    - r-base
    - r-fbasics
    - r-ggplot2
    - r-gprofiler
    - r-gridextra
    - r-pheatmap
    - r-reshape2
    - r-stabledist
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 3)'
  summary: 'OperaMate is a flexible R package dealing with the data generated by PerkinElmer''s Opera High Content Screening System. The functions include the data importing, normalization and quality control, hit detection and function analysis.'
