{% set version = "1.10.0" %}
{% set name = "nethet" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 77d59150477ab398fcf076191b7f27e75d5df7c0c3087cad86fc7b5dfb9355eb
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-limma
    - bioconductor-multtest
    - r-base
    - r-compquadform
    - r-genenet
    - r-ggm
    - r-ggplot2
    - r-glasso
    - r-glmnet
    - r-gsa
    - r-huge
    - r-icsnp
    - r-mclust
    - r-mvtnorm
    - r-network
    - r-parcor
    - gcc  # [linux]
    - llvm  # [osx]
  run:
    - bioconductor-limma
    - bioconductor-multtest
    - r-base
    - r-compquadform
    - r-genenet
    - r-ggm
    - r-ggplot2
    - r-glasso
    - r-glmnet
    - r-gsa
    - r-huge
    - r-icsnp
    - r-mclust
    - r-mvtnorm
    - r-network
    - r-parcor
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'Package nethet is an implementation of statistical solid methodology enabling the analysis of network heterogeneity from high-dimensional data. It combines several implementations of recent statistical innovations useful for estimation and comparison of networks in a heterogeneous, high-dimensional setting. In particular, we provide code for formal two-sample testing in Gaussian graphical models (differential network and GGM-GSA; Stadler and Mukherjee, 2013, 2014) and make a novel network-based clustering algorithm available (mixed graphical lasso, Stadler and Mukherjee, 2013).'
