{% set version = "1.10.0" %}
{% set name = "OmicsMarkeR" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: aba87e640f6a2837f39c8fe8f9da95789673f6d89000c325e0e4e4d987f4ff68
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'r-assertive >=0.3-0'
    - 'r-assertive.base >=0.0-1'
    - r-base
    - 'r-caret >=6.0-37'
    - 'r-catools >=1.14'
    - 'r-data.table >=1.9.4'
    - 'r-discriminer >=0.1-29'
    - 'r-e1071 >=1.6-1'
    - 'r-foreach >=1.4.1'
    - 'r-gbm >=2.1'
    - 'r-glmnet >=1.9-5'
    - 'r-pamr >=1.54.1'
    - 'r-permute >=0.7-0'
    - 'r-plyr >=1.8'
    - 'r-randomforest >=4.6-10'
  run:
    - 'r-assertive >=0.3-0'
    - 'r-assertive.base >=0.0-1'
    - r-base
    - 'r-caret >=6.0-37'
    - 'r-catools >=1.14'
    - 'r-data.table >=1.9.4'
    - 'r-discriminer >=0.1-29'
    - 'r-e1071 >=1.6-1'
    - 'r-foreach >=1.4.1'
    - 'r-gbm >=2.1'
    - 'r-glmnet >=1.9-5'
    - 'r-pamr >=1.54.1'
    - 'r-permute >=0.7-0'
    - 'r-plyr >=1.8'
    - 'r-randomforest >=4.6-10'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'Tools for classification and feature selection for ''omics'' level datasets.  It is a tool to provide multiple multivariate classification and feature selection techniques complete with multiple stability metrics and aggregation techniques.  It is primarily designed for analysis of metabolomics datasets but potentially extendable to proteomics and transcriptomics applications.'
