{% set version = "1.8.0" %}
{% set name = "miRLAB" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: bbf1b89aaf257d8ac290b4553b35b3901d2c566184311f0ed3a658d50334493a
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-impute
    - bioconductor-limma
    - bioconductor-roleswitch
    - r-base
    - r-energy
    - r-entropy
    - r-glmnet
    - r-gplots
    - r-hmisc
    - r-httr
    - r-pcalg
    - r-rcurl
    - r-stringr
  run:
    - bioconductor-impute
    - bioconductor-limma
    - bioconductor-roleswitch
    - r-base
    - r-energy
    - r-entropy
    - r-glmnet
    - r-gplots
    - r-hmisc
    - r-httr
    - r-pcalg
    - r-rcurl
    - r-stringr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>=2)'
  summary: 'Provide tools exploring miRNA-mRNA relationships, including popular miRNA target prediction methods, ensemble methods that integrate individual methods, functions to get data from online resources, functions to validate the results, and functions to conduct enrichment analyses.'
