{% set version = "1.4.0" %}
{% set name = "netprioR" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 03929ffa3ffec5078bf79e3f14ce11b3eb4904d34a48b738d10eb5a18a6ef7b2
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r-base
    - r-doparallel
    - r-dplyr
    - r-foreach
    - r-ggplot2
    - r-gridextra
    - r-matrix
    - r-proc
    - r-sparsemvn
  run:
    - r-base
    - r-doparallel
    - r-dplyr
    - r-foreach
    - r-ggplot2
    - r-gridextra
    - r-matrix
    - r-proc
    - r-sparsemvn
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'A model for semi-supervised prioritisation of genes integrating network data, phenotypes and additional prior knowledge about TP and TN gene labels from the literature or experts.'
