{% set version = "1.14.0" %}
{% set name = "scsR" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: eb92e270508d46c93ed9240e6788077939e2fdc960964af2a61b2fb5c2ceb817
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biocgenerics
    - bioconductor-biostrings
    - bioconductor-iranges
    - bioconductor-stringdb
    - r-base
    - r-ggplot2
    - r-hash
    - r-plyr
    - r-rcolorbrewer
    - r-sqldf
  run:
    - bioconductor-biocgenerics
    - bioconductor-biostrings
    - bioconductor-iranges
    - bioconductor-stringdb
    - r-base
    - r-ggplot2
    - r-hash
    - r-plyr
    - r-rcolorbrewer
    - r-sqldf
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'Corrects genome-wide siRNA screens for seed mediated off-target effect. Suitable functions to identify the effective seeds/miRNAs and to visualize their effect are also provided in the package.'
