{% set version = "1.8.0" %}
{% set name = "mAPKL" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 75adbc1359fb1158b47bd3da6a7a5492e99323b7969589d6517a29fac3c8c621
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - bioconductor-limma
    - bioconductor-multtest
    - bioconductor-reactome.db
    - r-apcluster
    - r-base
    - r-clustersim
    - r-e1071
    - r-igraph
    - r-parmigene
  run:
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - bioconductor-limma
    - bioconductor-multtest
    - bioconductor-reactome.db
    - r-apcluster
    - r-base
    - r-clustersim
    - r-e1071
    - r-igraph
    - r-parmigene
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'We propose a hybrid FS method (mAP-KL), which combines multiple hypothesis testing and affinity propagation (AP)-clustering algorithm along with the Krzanowski & Lai cluster quality index, to select a small yet informative subset of genes.'
