{% set version = "1.12.0" %}
{% set name = "MethylAid" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 913a902be2df9cf89738d262c50aafeec88b708136eb4597e9fecdce3413a2ce
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - 'bioconductor-minfi >=1.22.0'
    - bioconductor-summarizedexperiment
    - r-base
    - r-ggplot2
    - r-gridbase
    - r-hexbin
    - r-matrixstats
    - r-rcolorbrewer
    - r-shiny
  run:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - 'bioconductor-minfi >=1.22.0'
    - bioconductor-summarizedexperiment
    - r-base
    - r-ggplot2
    - r-gridbase
    - r-hexbin
    - r-matrixstats
    - r-rcolorbrewer
    - r-shiny
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'A visual and interactive web application using RStudio''s shiny package. Bad quality samples are detected using sample-dependent and sample-independent controls present on the array and user adjustable thresholds. In depth exploration of bad quality samples can be performed using several interactive diagnostic plots of the quality control probes present on the array. Furthermore, the impact of any batch effect provided by the user can be explored.'
