package:
    name: seecer
    version: 0.1.3  

build:
    number: 0

source:
    fn: SEECER-0.1.3.tar.gz
    url: http://sb.cs.cmu.edu/seecer/downloads/SEECER-0.1.3.tar.gz
    sha256: 47f3fd6da034e130d0ab0849c9e513b8b28326a346b06243179eb34baaa9f33f

requirements:
    build:
        - gcc
        - seqan-library
        - gsl {{ CONDA_GSL }}*
        - jellyfish
        - openmp
        - gnu-getopt
    run:
        - libgcc
        - seqan-library
        - gsl {{ CONDA_GSL }}*
        - jellyfish
        - openmp
        - gnu-getopt

test:
    commands:
        - run_seecer.sh -h | grep "Replace Ns and strip off read IDs"

about:
    home: http://sb.cs.cmu.edu/seecer/
    license: file
    license_file: SEECER/COPYING
    summary: Sequence error correction for RNA-Seq data.
extra:
    identifiers:
        - biotools:seecer
        - pmid:23558750
