{% set version = "1.16.0" %}
{% set name = "mitoODE" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: dbdfbc60fb815c712d72b78cd8c1def3c2372c8eb0a1fd6c6673d0653d8c7e86
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-mitoodedata
    - r-base
    - r-kernsmooth
    - r-mass
    - r-minpack.lm
    - gcc  # [linux]
    - llvm  # [osx]
  run:
    - bioconductor-mitoodedata
    - r-base
    - r-kernsmooth
    - r-mass
    - r-minpack.lm
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: LGPL
  summary: 'The package contains the methods to fit a cell-cycle model on cell count data and the code to reproduce the results shown in our paper  "Dynamical modelling of phenotypes in a genome-wide RNAi live-cell imaging assay" by Pau, G., Walter, T., Neumann, B., Heriche, J.-K., Ellenberg, J., & Huber, W., BMC Bioinformatics (2013), 14(1), 308. doi:10.1186/1471-2105-14-308'
