{% set version = "1.10.0" %}
{% set name = "netbenchmark" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 2139966cddea1283a3c113a22ff64f1669ab8936735b7dd10172a347f5ae729c
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-grndata >=0.99.3'
    - bioconductor-minet
    - r-base
    - r-c3net
    - r-corpcor
    - r-fdrtool
    - r-genenet
    - r-matrix
    - r-pcit
    - r-pracma
    - r-randomforest
    - 'r-rcpp >=0.11.0'
    - gcc  # [linux]
    - llvm  # [osx]
  run:
    - 'bioconductor-grndata >=0.99.3'
    - bioconductor-minet
    - r-base
    - r-c3net
    - r-corpcor
    - r-fdrtool
    - r-genenet
    - r-matrix
    - r-pcit
    - r-pracma
    - r-randomforest
    - 'r-rcpp >=0.11.0'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'CC BY-NC-SA 4.0'
  summary: 'This package implements a benchmarking of several gene network inference algorithms from gene expression data.'
