{% set version = "3.10.2" %}
{% set name = "MSstats" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: b1875d57946979d2b40da3f0cf5061ffed40227f23ff0e0cb51bf8805d129052
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-limma
    - bioconductor-marray
    - bioconductor-msnbase
    - bioconductor-preprocesscore
    - r-base
    - r-data.table
    - r-dosnow
    - r-foreach
    - r-ggplot2
    - r-ggrepel
    - r-gplots
    - r-lme4
    - r-minpack.lm
    - r-rcpp
    - r-reshape2
    - r-snow
    - r-survival
    - gcc  # [linux]
    - llvm  # [osx]
  run:
    - bioconductor-limma
    - bioconductor-marray
    - bioconductor-msnbase
    - bioconductor-preprocesscore
    - r-base
    - r-data.table
    - r-dosnow
    - r-foreach
    - r-ggplot2
    - r-ggrepel
    - r-gplots
    - r-lme4
    - r-minpack.lm
    - r-rcpp
    - r-reshape2
    - r-snow
    - r-survival
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'A set of tools for statistical relative protein significance analysis in DDA, SRM and DIA experiments.'
