{% set version = "1.16.1" %}
{% set name = "openCyto" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 5b8fc73b35e689913ae3235227a4d9f42d593b7a6b8288212f118a163006fde3
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biobase
    - 'bioconductor-flowclust >=3.11.4'
    - 'bioconductor-flowcore >=1.31.17'
    - 'bioconductor-flowstats >=3.29.1'
    - bioconductor-flowviz
    - 'bioconductor-flowworkspace >=3.17.43'
    - bioconductor-graph
    - 'bioconductor-ncdfflow >=2.11.34'
    - bioconductor-rbgl
    - r-base
    - r-clue
    - r-data.table
    - r-gtools
    - r-ks
    - r-lattice
    - r-mass
    - r-plyr
    - r-r.utils
    - r-rcolorbrewer
    - r-rcpp
    - r-rrcov
    - gcc  # [linux]
    - llvm  # [osx]
  run:
    - bioconductor-biobase
    - 'bioconductor-flowclust >=3.11.4'
    - 'bioconductor-flowcore >=1.31.17'
    - 'bioconductor-flowstats >=3.29.1'
    - bioconductor-flowviz
    - 'bioconductor-flowworkspace >=3.17.43'
    - bioconductor-graph
    - 'bioconductor-ncdfflow >=2.11.34'
    - bioconductor-rbgl
    - r-base
    - r-clue
    - r-data.table
    - r-gtools
    - r-ks
    - r-lattice
    - r-mass
    - r-plyr
    - r-r.utils
    - r-rcolorbrewer
    - r-rcpp
    - r-rrcov
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'This package is designed to facilitate the automated gating methods in sequential way to mimic the manual gating strategy.'
