{% set version = "1.12.0" %}
{% set name = "PAA" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: f07636476c51f388bcad2b4096599bd811f9315a9695fc476b0bd49bfe74cfa0
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-limma
    - bioconductor-sva
    - r-base
    - r-e1071
    - r-gplots
    - r-gtools
    - r-mass
    - r-mrmre
    - r-randomforest
    - 'r-rcpp >=0.11.6'
    - r-rocr
    - gcc  # [linux]
    - llvm  # [osx]
  run:
    - bioconductor-limma
    - bioconductor-sva
    - r-base
    - r-e1071
    - r-gplots
    - r-gtools
    - r-mass
    - r-mrmre
    - r-randomforest
    - 'r-rcpp >=0.11.6'
    - r-rocr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'BSD_3_clause + file LICENSE'
  summary: 'PAA imports single color (protein) microarray data that has been saved in gpr file format - esp. ProtoArray data. After preprocessing (background correction, batch filtering, normalization) univariate feature preselection is performed (e.g., using the "minimum M statistic" approach - hereinafter referred to as "mMs"). Subsequently, a multivariate feature selection is conducted to discover biomarker candidates. Therefore, either a frequency-based backwards elimination aproach or ensemble feature selection can be used. PAA provides a complete toolbox of analysis tools including several different plots for results examination and evaluation.'
