{% set version = "1.29.0" %}
{% set name = "ontoCAT" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 0f02fdc72b966ccf81c42140ad93d824a732c17fd620f4e4132222a0015bfa14
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r-base
    - r-rjava
  run:
    - r-base
    - r-rjava
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'Apache License 2.0'
  summary: 'The ontoCAT R package provides a simple interface to ontologies described in widely used standard formats, stored locally in the filesystem or accessible online.'
