{% set version = "1.10.0" %}
{% set name = "msa" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 8574052f76dc04d9d11006e182a3085848cf1cbc9319df27934ff7acf5a79f95
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biocgenerics
    - 'bioconductor-biostrings >=2.40.0'
    - 'bioconductor-iranges >=1.20.0'
    - bioconductor-s4vectors
    - r-base
    - 'r-rcpp >=0.11.1'
    - gcc  # [linux]
    - llvm  # [osx]
  run:
    - bioconductor-biocgenerics
    - 'bioconductor-biostrings >=2.40.0'
    - 'bioconductor-iranges >=1.20.0'
    - bioconductor-s4vectors
    - r-base
    - 'r-rcpp >=0.11.1'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'The ''msa'' package provides a unified R/Bioconductor interface to the multiple sequence alignment algorithms ClustalW, ClustalOmega, and Muscle. All three algorithms are integrated in the package, therefore, they do not depend on any external software tools and are available for all major platforms. The multiple sequence alignment algorithms are complemented by a function for pretty-printing multiple sequence alignments using the LaTeX package TeXshade.'
