{% set version = "1.10.0" %}
{% set name = "RCyjs" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 8f87c7ecced1b02fdca2bda75460d1f252d7a39d5b01eef6908970bfc4809e6e
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biocgenerics
    - 'bioconductor-browserviz >=1.1.7'
    - 'bioconductor-graph >=1.44.0'
    - r-base
    - r-base64enc
    - 'r-httpuv >=1.3.2'
    - r-igraph
    - 'r-jsonlite >=0.9.15'
    - 'r-rcpp >=0.11.5'
    - gcc  # [linux]
    - llvm  # [osx]
  run:
    - bioconductor-biocgenerics
    - 'bioconductor-browserviz >=1.1.7'
    - 'bioconductor-graph >=1.44.0'
    - r-base
    - r-base64enc
    - 'r-httpuv >=1.3.2'
    - r-igraph
    - 'r-jsonlite >=0.9.15'
    - 'r-rcpp >=0.11.5'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'Interactive viewing and exploration of graphs, connecting R to Cytoscape.js.'
