{% set version = "1.26.0" %}
{% set name = "spliceSites" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 1d5db23f25b079138211978a8a8c06d234508862c9c369c1259df8dd26075ba5
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - 'bioconductor-biostrings >=2.28.0'
    - bioconductor-iranges
    - bioconductor-seqlogo
    - r-base
    - r-doby
    - 'r-rbamtools >=2.14.3'
    - 'r-refgenome >=1.6.0'
    - gcc  # [linux]
    - llvm  # [osx]
  run:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - 'bioconductor-biostrings >=2.28.0'
    - bioconductor-iranges
    - bioconductor-seqlogo
    - r-base
    - r-doby
    - 'r-rbamtools >=2.14.3'
    - 'r-refgenome >=1.6.0'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'Performs splice centered analysis on RNA-seq data.'
