{% set version = "1.28.0" %}
{% set name = "ArrayExpressHTS" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 356affd837133f0eb85eb525728a683d2efa34f26fa36c5a479c77cffdeb1613
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-biomart
    - bioconductor-biostrings
    - bioconductor-deseq
    - bioconductor-edger
    - bioconductor-genomicranges
    - bioconductor-iranges
    - 'bioconductor-rsamtools >=1.19.36'
    - bioconductor-shortread
    - r-base
    - r-bitops
    - r-hmisc
    - r-r2html
    - r-rcolorbrewer
    - r-rjava
    - r-sampling
    - r-sendmailr
    - r-snow
    - r-svmisc
    - r-xml
    - gcc  # [linux]
    - llvm  # [osx]
  run:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-biomart
    - bioconductor-biostrings
    - bioconductor-deseq
    - bioconductor-edger
    - bioconductor-genomicranges
    - bioconductor-iranges
    - 'bioconductor-rsamtools >=1.19.36'
    - bioconductor-shortread
    - r-base
    - r-bitops
    - r-hmisc
    - r-r2html
    - r-rcolorbrewer
    - r-rjava
    - r-sampling
    - r-sendmailr
    - r-snow
    - r-svmisc
    - r-xml
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'Artistic License 2.0'
  summary: 'RNA-Seq processing pipeline for public ArrayExpress experiments or local datasets'
