{% set version = "1.22.0" %}
{% set name = "NarrowPeaks" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: a8f696281df63e0415391577db517dc7b8f13d30f7726ed740a38936597322aa
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biocgenerics
    - bioconductor-csar
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - r-base
    - r-fda
    - r-icsnp
    - gcc  # [linux]
    - llvm  # [osx]
  run:
    - bioconductor-biocgenerics
    - bioconductor-csar
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - r-base
    - r-fda
    - r-icsnp
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'The package applies a functional version of principal component analysis (FPCA) to: (1) Postprocess data in wiggle track format, commonly produced by generic ChIP-seq peak callers, by applying FPCA over a set of read-enriched regions (ChIP-seq peaks). This is done to study variability of the the peaks, or to shorten their genomic locations accounting for a given proportion of variation among the enrichment-score profiles. (2) Analyse differential variation between multiple ChIP-seq samples with replicates. The function ''narrowpeaksDiff'' quantifies differences between the shapes, and uses Hotelling''s T2 tests on the functional principal component scores to identify significant differences across conditions. An application of the package for Arabidopsis datasets is described in Mateos, Madrigal, et al. (2015) Genome Biology: 16:31.'
