{% set version = "1.4.0" %}
{% set name = "readat" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 4a553daa24c06e3418d96c85e664c080ff7395ef8c3124e38877d6694659f182
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-biobase >=2.34.0'
    - 'bioconductor-summarizedexperiment >=1.4.0'
    - 'r-assertive.base >=0.0-7'
    - 'r-assertive.files >=0.0-2'
    - 'r-assertive.numbers >=0.0-2'
    - 'r-assertive.properties >=0.0-4'
    - 'r-assertive.sets >=0.0-3'
    - 'r-assertive.types >=0.0-3'
    - r-base
    - 'r-data.table >=1.10.4'
    - 'r-dplyr >=0.5.0'
    - 'r-magrittr >=1.5'
    - 'r-openxlsx >=4.0.17'
    - 'r-pathological >=0.1-2'
    - 'r-reshape2 >=1.4.2'
    - 'r-stringi >=1.1.5'
    - 'r-testthat >=1.0.2'
    - 'r-tidyr >=0.6.2'
  run:
    - 'bioconductor-biobase >=2.34.0'
    - 'bioconductor-summarizedexperiment >=1.4.0'
    - 'r-assertive.base >=0.0-7'
    - 'r-assertive.files >=0.0-2'
    - 'r-assertive.numbers >=0.0-2'
    - 'r-assertive.properties >=0.0-4'
    - 'r-assertive.sets >=0.0-3'
    - 'r-assertive.types >=0.0-3'
    - r-base
    - 'r-data.table >=1.10.4'
    - 'r-dplyr >=0.5.0'
    - 'r-magrittr >=1.5'
    - 'r-openxlsx >=4.0.17'
    - 'r-pathological >=0.1-2'
    - 'r-reshape2 >=1.4.2'
    - 'r-stringi >=1.1.5'
    - 'r-testthat >=1.0.2'
    - 'r-tidyr >=0.6.2'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'This package contains functionality to import, transform and annotate data from ADAT files generated by the SomaLogic SOMAscan platform.'
