package:
    name: crisp
    version: 1.0  

build:
    number: 0

source:
    fn: crisp-bf1c61e86d201971e781445b6f35604e9ef4865e.tar.gz
    url: https://github.com/vibansal/crisp/archive/bf1c61e86d201971e781445b6f35604e9ef4865e.tar.gz
    sha256: f31a58e7113200bf6f6f2225937bc7e006123095d416b1ea317ab23434fec464

requirements:
    build:
        - gcc
        - ncurses
    run:
        - libgcc
        - ncurses

test:
    commands:
        - CRISP-genotypes | grep CRISP
about:
    home: https://bansal-lab.github.io/software/crisp.html
    license: MIT
    license_file: LICENSE
    summary: Identifies rare and common variants in pooled sequencing data
extra:
    identifiers:
        - biotools:crisp
        - doi:10.1093/bioinformatics/btq214
