{% set version = "1.56.0" %}
{% set name = "reb" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: bde4c02460d16d2761bf64f40a201799e356c0a15f653ed7ac6e6891cfc9096a
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biobase
    - 'bioconductor-idiogram >=1.5.3'
    - r-base
    - gcc  # [linux]
    - llvm  # [osx]
  run:
    - bioconductor-biobase
    - 'bioconductor-idiogram >=1.5.3'
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'A set of functions to dentify regional expression biases'
