{% set version = "1.14.0" %}
{% set name = "polyester" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: ba4f3221e9a8589cb1ce94b35ebb33f9261b0990b54862032da165eb989db4df
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-biostrings >=2.32.0'
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-s4vectors
    - bioconductor-zlibbioc
    - r-base
    - r-logspline
  run:
    - 'bioconductor-biostrings >=2.32.0'
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-s4vectors
    - bioconductor-zlibbioc
    - r-base
    - r-logspline
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'This package can be used to simulate RNA-seq reads from differential expression experiments with replicates. The reads can then be aligned and used to perform comparisons of methods for differential expression.'
