{% set version = "1.8.0" %}
{% set name = "SICtools" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: c8e1db6c7b782e6f9b0c11e3c07d20934297c3c8f094451aad25295e06197558
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-biostrings >=2.32.1'
    - 'bioconductor-genomicranges >=1.22.4'
    - 'bioconductor-iranges >=2.4.8'
    - 'bioconductor-rsamtools >=1.18.1'
    - r-base
    - 'r-doparallel >=1.0.8'
    - 'r-matrixstats >=0.10.0'
    - 'r-plyr >=1.8.3'
    - 'r-stringr >=0.6.2'
    - gcc  # [linux]
    - llvm  # [osx]
  run:
    - 'bioconductor-biostrings >=2.32.1'
    - 'bioconductor-genomicranges >=1.22.4'
    - 'bioconductor-iranges >=2.4.8'
    - 'bioconductor-rsamtools >=1.18.1'
    - r-base
    - 'r-doparallel >=1.0.8'
    - 'r-matrixstats >=0.10.0'
    - 'r-plyr >=1.8.3'
    - 'r-stringr >=0.6.2'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>=2)'
  summary: 'This package is to find SNV/Indel differences between two bam files with near relationship in a way of pairwise comparison thourgh each base position across the genome region of interest. The difference is inferred by fisher test and euclidean distance, the input of which is the base count (A,T,G,C) in a given position and read counts for indels that span no less than 2bp on both sides of indel region.'
