{% set version = "1.24.0" %}
{% set name = "rqubic" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: b5b353f7b80d77de13c8f1f5ae4a53e2c1768c980a71b0f9267ebd65d98dc894
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - r-base
    - r-biclust
    - gcc  # [linux]
    - llvm  # [osx]
  run:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - r-base
    - r-biclust
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'This package implements the QUBIC algorithm introduced by Li et al. for the qualitative biclustering with gene expression data.'
