package:
    name: fastqz
    version: 1.5  

build:
    number: 0

source:
    url: http://mattmahoney.net/dc/fastqz/fastqz15.cpp
    sha256: 67ead53084fe96bad337e66f4447070c113b71726f7e5e586bec0ade4a5b85dd

requirements:
    build:
        - {{ compiler('c') }}
    host:
        - wget
        - unzip

test:
    commands:
        - fastqz 2>&1 | grep -q "fastqz v1.5 FASTQ compressor"
        - fapack 2>&1 | grep -q "To pack FASTA files"

about:
    home: http://mattmahoney.net/dc/fastqz/
    license: BSD-2
    summary: fastqz is a compressor for the most common (Sanger format) FASTQ files produced by DNA sequencing machines. It may be used with a reference genome for better compression.
extra:
    identifiers:
        - biotools:Fastqz
        - doi:10.1371/journal.pone.0059190
