{% set version = "1.24.0" %}
{% set name = "ReQON" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 1401bafb56f5da34142a84ff950797d50f6eb9263c9ded8d726cfe3e85074f3b
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-rsamtools
    - bioconductor-seqbias
    - r-base
    - r-rjava
  run:
    - bioconductor-rsamtools
    - bioconductor-seqbias
    - r-base
    - r-rjava
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'Algorithm for recalibrating the base quality scores for aligned sequencing data in BAM format.'
