package:
    name: genomictools
    version: 1.0  

build:
    number: 0

source:
    url: https://github.com/tsirigos/ibm-cbc-genomic-tools/archive/d2cbeeec42481f1500bd7b98a7857df93881d85a.zip
    sha256: ca403238305eb145d003f041bf5a35a0c7cd427eb0919ee23857b69bc95a225b

requirements:
    build:
        - {{ compiler('cxx') }}
    host:
        - gsl
        - zlib
        - samtools
    run:
        - zlib
        - samtools

test:
    commands:
        - gtools_hic 2>&1 | grep USAGE

about:
    home: http://code.google.com/p/ibm-cbc-genomic-tools/
    license: GPL-2
    summary: GenomicTools is a platform for the analysis and manipulation of high-throughput sequencing data such as RNA-seq and ChIP-seq.
extra:
    identifiers:
        - biotools:genomictools
        - doi:10.1093/bioinformatics/btr646
