package:
    name: lightstringgraph
    version: 1  

build:
    number: 0

source: 
    url: https://github.com/AlgoLab/LightStringGraph/archive/v0.4.0.tar.gz
    sha256: 7a1530b147269b285875687fecaecbfd4d94c3db04d33ddeb1d0624547317b00

requirements:
    build:
        - {{ compile('cxx') }}

test:
    commands:
        - graph2asqg 2>&1 | grep Usage
        - lsg 2>&1 | grep Usage
        - redbuild 2>&1 | grep Usage

about:
    home: http://lsg.algolab.eu/
    license: file
    license_file: COPYING
    summary: LightStringGraphs (LSG) is an external memory string graph construction tool.
extra:
    identifiers:
        - biotools:lightstringgraph
        - doi:10.1007/978-3-662-44753-6_23
