{% set version = "1.18.2" %}
{% set name = "SeqArray" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 7f8af394c03c1ab77d5a6a0317ef3220fab648e049d96ff254c4a96162288017
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biostrings
    - 'bioconductor-gdsfmt >=1.10.1'
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - r-base
    - gcc  # [linux]
    - llvm  # [osx]
  run:
    - bioconductor-biostrings
    - 'bioconductor-gdsfmt >=1.10.1'
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'Big data management of whole-genome sequencing variant calls with thousands of individuals: genotypic data (e.g., SNVs, indels and structural variation calls) and annotations in SeqArray files are stored in an array-oriented and compressed manner, with efficient data access using the R programming language.'
